### PR TITLE
Added io redirection in the gui

### LINKED ISSUE #93: Input/Output Files for GUI mode
**As a** user
**I want** to define an input file to use instead of std input, even in gui mode. Or an output file for gui mode.
**So that** I don't have to put in a bunch of input when it isn't necessary. And so I can get output to a place where it can be viewed in summary.

**Request Description**
Self explanatory

### PR DESCRIPTION
**Pull request by WyattRoss**
closes #93

### CODE REVIEW

**Review by TrevorBrunette — APPROVED** [review]
LGTM

**Review by TrevorBrunette — CHANGES_REQUESTED** [review]
NVM -- it does not work with input when using step through functionality.

**Comment by WyattRoss** [comment]
> NVM -- it does not work with input when using step through functionality.

Clarify? I played around with stepthrough in the matrix multiplication demo and input worked fine for me. Could you give a simple example of code and input which causes it to break.

**Comment by TrevorBrunette** [comment]
> > NVM -- it does not work with input when using step through functionality.
> 
> Clarify? I played around with stepthrough in the matrix multiplication demo and input worked fine for me. Could you give a simple example of code and input which causes it to break.

I should have been more clear on the circumstances. After you run for instance the matrix multiplication program to 
termination with input in the GUI (and the state is STOPPPED or IDLE) when using step to start the program, the input no longer works properly.

**Review by TrevorBrunette — APPROVED** [review]
Seems good now -- squash merge it.

**Pull request merged**
