### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Added support for linting. It will automatically format the code during build.

Additionally you can run  mvn formatter: format to run linter.

### CODE REVIEW

**Comment by TrevorBrunette** [comment]
@WyattRoss can you try running the GUI and sample code on this to make sure the format changes didn't break anything? Try to be thorough.

**Comment by TrevorBrunette** [comment]
@tarunsamanta2k20 how would we go about changing the formatting that this applies? Is there a configuration file?

**Comment by tarunsamanta2k20** [comment]
I already applied that's why so many file changed. 

You can simply build the application using 

mvn assembly ..... Command.

**Comment by WyattRoss** [comment]
LGTM

**Review by WyattRoss — DISMISSED** [review]

**Pull request closed without merging**
