### PR TITLE
#44 issue:Error Message Line Numbers

### PR DESCRIPTION
**Pull request by ChelseaChanu**

### CODE REVIEW

**Review by WyattRoss — CHANGES_REQUESTED** [review]
This is the kind of change we're looking for, it just doesn't deal with it everywhere. Check line 162 of `Lexer.java`. Fix that line and you'll be good to go.

**Comment by ChelseaChanu** [comment]
> This is the kind of change we're looking for, it just doesn't deal with it everywhere. Check line 162 of `Lexer.java`. Fix that line and you'll be good to go.

Hi, I have made changes in Lexer.java line 162.

**Review by TrevorBrunette — APPROVED** [review]
Completes request requirements, LGTM

**Review by WyattRoss — APPROVED** [review]
Looks good!

**Pull request merged**
